### ISSUE TITLE
Error on trying to follow "Get Started With Windows" instructions 

### ISSUE THREAD

**Issue by edzhuang** [microsoft/react-native-windows#10155]
### Problem Description

When running the app in visual studio code, I encountered an error.

### Steps To Reproduce

1. Follow the instructions here https://microsoft.github.io/react-native-windows/docs/getting-started and run on visual studio code

### Expected Results

The app running.

### CLI version

7.0.3

### Environment

```markdown
System:
    OS: Windows 10 10.0.22000
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Memory: 7.23 GB / 15.83 GB
  Binaries:
    Node: 16.14.2 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.9.0 - D:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Enabled
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.16299.0, 10.0.18362.0, 10.0.19041.0, 10.0.22616.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32602.291 (Visual Studio Community 2019), 17.2.32602.215 (Visual Studio Community 2022)
  Languages:
    Java: 11.0.14.1 - C:\Program Files\OpenJDK\openjdk-11.0.14.1_1\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: 0.68.5 => 0.68.5
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

Here is the output of react-native run-windows --logging.
```
Utilization:          99.9     Average Utilization: 99.9
√ Building Solution
 √ React-Native Server already started
 √ Enabling Developer Mode
 ERROR: ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryPreviewImportsStateMachine(PartManager partManager, ComposablePart part, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.PreviewImports(ComposablePart part, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at Microsoft.VisualStudio.Deployment.Deployer.Deploy()
ERROR: Exceptions from the reflection loader:
ERROR: FileLoadException: Could not load file or assembly 'NuGet.VisualStudio.Contracts, Version=17.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
ERROR: ArgumentNullException: Value cannot be null.
Parameter name: format
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.WriteLine(String format, Object[] arg)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
   at System.Console.WriteLine(String format, Object[] arg)
   at Microsoft.VisualStudio.Deployment.Deployer.Microsoft.VisualStudio.Deployment.ILogger.Log(Level level, String format, Object[] args)
   at Microsoft.VisualStudio.Deployment.Deployer.Deploy()
× Deploying
 × Failed to deploy: Deploying D:\Users\zhuan\GeekyStuff\WebDev\facetouching\windows\x64\Debug\facetouching\facetouching.build.appxrecipe - exit error code 100
 i Gathering MSBuild data for telemetry.
 i Loading properties from msbuildproperties.g.json
Command failed with error DeployRecipeFailure: Deploying D:\Users\zhuan\GeekyStuff\WebDev\facetouching\windows\x64\Debug\facetouching\facetouching.build.appxrecipe - exit error code 100
Your telemetry sessionId was 4b74f3768e0ce19af2a4d5123de38325
```

**Comment by chrisglein** [comment]
The failure actually seems to be in Visual Studio deployment:
```
at Microsoft.VisualStudio.Deployment.Deployer.Deploy()
```
And it's happening within the Visual Studio 2022 version.
@asklar Can you loop in the right VS contact to help look at this?

**Comment by EdZ543** [comment]
I have upgraded and it indeed does work as intended now.

**Comment by Yajur-Grover** [comment]
I am also hitting this issue when trying to build a Fabric app on RNW version [canary-761](https://www.npmjs.com/package/react-native-windows/v/0.0.0-canary.761) and running on VS 2022 17.8.7 (following the instructions to use the cpp-app template to create a new app [here](https://github.com/microsoft/react-native-windows/wiki/Using-the-new-architecture-templates): 

```
√ Building Solution
 √ Starting the React-Native Server
 √ Enabling Developer Mode
 ERROR: ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryPreviewImportsStateMachine(PartManager partManager, ComposablePart part, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.PreviewImports(ComposablePart part, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at Microsoft.VisualStudio.Deployment.Deployer.Deploy()
ERROR: Exceptions from the reflection loader:
ERROR: FileLoadException: Could not load file or assembly 'NuGet.VisualStudio.Contracts, Version=17.8.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
ERROR: ArgumentNullException: Value cannot be null.
Parameter name: format
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.WriteLine(String format, Object[] arg)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(String format, Object[] arg)
   at System.Console.WriteLine(String format, Object[] arg)
   at Microsoft.VisualStudio.Deployment.Deployer.Microsoft.VisualStudio.Deployment.ILoggerSink.Log(Level level, String format, Object[] args)
   at Microsoft.VisualStudio.Deployment.Deployer.Deploy()
× Deploying
 × Failed to deploy: Deploying C:/Users/yajurgrover/new-account-repos/react-native-gallery/testFabric/windows/testFabric.Package/bin/x64/Debug/testFabric.Package.build.appxrecipe - exit error code 100
 i Gathering MSBuild data for telemetry.
 i Loading properties from msbuildproperties.g.json
Command failed with error DeployRecipeFailure: Deploying C:/Users/yajurgrover/new-account-repos/react-native-gallery/testFabric/windows/testFabric.Package/bin/x64/Debug/testFabric.Package.build.appxrecipe - exit error code 100
Your telemetry sessionId was 4c49a6aaa6b7c4cac75a944e96057f19
error Command failed with exit code 2412.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Updating VS 2022 version to 17.9.0 to see if that resolves the issue.

**Comment by Yajur-Grover** [comment]
> Updating VS 2022 version to 17.9.0 to see if that resolves the issue.

Upgrading to 17.9.0 resolves the issue for me  - I am able to successfully build the app.

**Comment by jonthysell** [comment]
And we're back with this failing in 17.10.2.

**Comment by jonthysell** [comment]
Opened a new bug to track the current iteration of this.

**Comment by Kamek437** [comment]
Link it would you?

**Comment by famaster** [comment]
how to fix this then? can you downgrade visual studio version?

**Comment by Kamek437** [comment]
After you try to build there will be a cmd.exe window open for debugging, when it's showing you open the project in visual studio and hit build and it will deploy to the cmd.exe window and run correctly.
