### ISSUE TITLE
react-native windows gives Unhandled 'error' event

### ISSUE THREAD

**Issue by Driky** [Microsoft/react-native-windows#1092]
Just created a project to give react-native-windows a try. When I execute `react-native windows` I get : 
```
Error: write EINVAL
    at exports._errnoException (util.js:1022:11)
    at WriteStream.Socket._writeGeneric (net.js:715:26)
    at WriteStream.Socket._write (net.js:734:8)
    at doWrite (_stream_writable.js:334:12)
    at writeOrBuffer (_stream_writable.js:320:5)
    at WriteStream.Writable.write (_stream_writable.js:247:11)
    at WriteStream.Socket.write (net.js:661:40)
    at WriteStream.stream.write (G:\projects\typescript\v41\node_modules\ansi\lib\newlines.js:36:21)
    at Object.execFileSync (child_process.js:506:20)
    at Object.run (G:/projects/typescript/v41/node_modules/react-native/local-cli/cliEntry.js:156:16)
```

I used this [instruction ](https://github.com/Microsoft/react-native-windows/issues/1062)to make my project : 
```
react-native init v41 --version 0.41.2
cd v41
npm i --save-dev rnpm-plugin-windows
react-native windows
```
My node version:
```
node -v
v7.1.0
```

**Comment by matthargett** [comment]
* What OS and shell are you running the commands from? 
* If you're on Windows 7, is the drive the commands are running against formatted as exFAT or NTFS?
* What's the full path your running the commands from? Does it have spaces or unicode characters?

**Comment by sayar** [comment]
@Driky, has your issue been resolved?

**Comment by rozele** [comment]
Closing due to inactivity.
