### ISSUE TITLE
PanResponder nested inside ScrollView does not receive touch events

### ISSUE THREAD

**Issue by adi1133** [Microsoft/react-native-windows#1140]
I have tried to follow [this blog post](http://browniefed.com/blog/react-native-pan-responder-inside-of-a-scrollview/) in order to be able to use the `PanResponder` inside of a `ScrollView` to process touch events and to prevent the `ScrollView` from scrolling.
I have run the same codebase using React Native Windows and React Native on Android, and have discovered that the suggested fix from the blog post is only usable on Android.
I have created a small project to help reproduce the issue. 

Steps to reproduce: 
- [Download the sample codebase](https://drive.google.com/file/d/0B7VHcjwhSRPNMzFHbks2MUQ4dWs/view?usp=sharing)
- Install the node modules (`npm install` or `yarn install`)
- Run the app on Windows and Android
- Using a touch screen, drag the yellow squares left and right, the ScrollView will move horizontally
- Drag the red square. On Android touch events will be processed and Scrolling disabled, on Windows touch events are not processed and scrolling remains active.

**Comment by rozele** [comment]
@adi1133 I think this is due to the fact that we don't properly implement `setJSResponder` on the `UIManager`, which I believe is used to cancel scrolling.  Have you had any luck debugging this or getting it to work?

**Comment by rozele** [comment]
This is the same as https://github.com/Microsoft/react-native-windows/issues/569

**Comment by rozele** [comment]
@adi1133 I think the theory above is correct. We need to (selectively) call `CancelDirectManipulations` on the targeted JSResponder UIElement. I've been trying to prototype this today, but I'm running into an issue where the `setJSResponder` API seems a bit too eager, and I cancel the direct manipulations too often, causing making the scroll behavior janky. I'm trying to figure out what the exact expectations of `setJSResponder` are.

**Comment by rozele** [comment]
@adi1133 can you take a look at the PR https://github.com/Microsoft/react-native-windows/pull/1228 and see if using the `manipulationModes` View prop will resolve your PanResponder issues? You'll need to integrate the PR with your branch.

**Comment by adi1133** [comment]
@rozele I am in vacation, will get back with some answers on July 28

**Comment by rozele** [comment]
@adi1133 I'm closing out this issue, if you can upgrade to react-native@0.47, please try the `manipulationMode` prop. If you're locked into a specific react-native version, let me know and I can try to cherry-pick the commit back to that version.

**Comment by adi1133** [comment]
Hi @rozele, thank you for your support.

I am stuck on react-native@0.43.3, when I try the latest version (0.47.0) I face this error:
```
Bundling `index.windows.js`  [development, non-minified, hmr disabled]  0.0% (0/168), failed.
Error: ENOENT: no such file or directory, open 'C:\Users\User\repos\reactnativeuwp\node_modules\react-native-windows\Libraries\Utilities\BackAndroid.windows.js'
    at Object.fs.openSync (fs.js:651:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Module._readSourceCode (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\Module.js:205:29)
    at Module._getCacheProps (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\Module.js:395:29)
    at Module._readFromTransformCache (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\Module.js:345:29)
    at Module.readCached (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\Module.js:332:19)
    at ResolutionRequest.preprocessModule (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:306:27)
    at ResolutionRequest._preprocessPotentialDependencies (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:290:27)
    at ResolutionRequest.getOrderedDependencies (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\DependencyGraph\ResolutionRequest.js:142:12)
    at DependencyGraph.getDependencies (C:\Users\User\repos\reactnativeuwp\node_modules\metro-bundler\src\node-haste\DependencyGraph.js:284:4424)
```

How can I run a version that supports `manipulationModes`?
How do I use `manipulationModes` together with a `PanResponer` that wants to capture movement events that happen in the same axis as the `ScrollView`?
