### ISSUE TITLE
Integration Test app fails to load in Debug

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11562]
### Problem Description

The integration-test-app builds and starts. Metro bundles successfully. However the app errors when the bundle is actually loaded and executed. This happens whether using Chakra or Hermes.

Example using Hermes:

From Metro:

```
info Launching Dev Tools...
 BUNDLE  ./index.tsx

 BUNDLE  ./index.tsx

 LOG  JavaScript logs will appear in your browser console
Error: Unable to resolve module ./debugger-ui/debuggerWorker.aca173c4 from C:\code\rnw\packages\integration-test-app/.:

None of these files exist:
  * debugger-ui\debuggerWorker.aca173c4(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
  * debugger-ui\debuggerWorker.aca173c``4\index(.native|.native.js|.js|.native.jsx|.jsx|.native.json|.json|.native.ts|.ts|.native.tsx|.tsx)
    at ModuleResolver.resolveDependency (C:\code\rnw\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:114:15)
    at DependencyGraph.resolveDependency (C:\code\rnw\node_modules\metro\src\node-haste\DependencyGraph.js:271:43)
    at C:\code\rnw\node_modules\metro\src\lib\transformHelpers.js:171:21
    at Server._resolveRelativePath (C:\code\rnw\node_modules\metro\src\Server.js:1132:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server._explodedSourceMapForURL (C:\code\rnw\node_modules\metro\src\Server.js:1080:35)
    at async Promise.all (index 1)
    at async Server._symbolicate (C:\code\rnw\node_modules\metro\src\Server.js:1031:26)
    at async Server._processRequest (C:\code\rnw\node_modules\metro\src\Server.js:417:7)
```

<img width="586" alt="image" src="https://user-images.githubusercontent.com/10852185/236342808-b1df2834-9b65-409a-8ebb-0ae8b3bb213b.png">

<img width="586" alt="image" src="https://user-images.githubusercontent.com/10852185/236342853-2699ecad-b12b-4378-8146-e062aded517c.png">

### Steps To Reproduce

1. Clone repo.
2. cd packages/integration-test-app
3. `yarn windows --no-autolink --arch x86 --logging`

### Expected Results

App launches and loads

### CLI version

12.0.0-alpha.0

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.25352
  CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Memory: 6.78 GB / 15.84 GB
Binaries:
  Node:
    version: 16.18.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.19.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.16299.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 16.11.33529.622 (Visual Studio Enterprise 2019)
    - 17.5.33530.505 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by jonthysell** [comment]
I have confirmed that everything loads fine in Release, so definitely Debug only

**Comment by acoates-ms** [comment]
Can you try removing this line?
https://github.com/microsoft/react-native-windows/blob/657672e5ab8a3d8658822fb41c8645e643f155f5/packages/integration-test-app/tests/MountComponentTests.tsx#L133
