### ISSUE TITLE
RestoreUseStaticGraphEvaluation no longer works to build RNW in Visual Studio >= 17.6, unable to build

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#11670]
### Problem Description

Starting in Visual Studio 17.6, if you try to build `Microsoft.ReactNative.sln` you'll get the following failure in the `NuGet.RestoreEx.targets` file:

```
C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error : '{' is an unexpected token. The expected token is '"' or '''. Line 2, position 31.
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.ParseAttributes()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.ParseElement()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlTextReaderImpl.ParseElementContent()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Xml.XmlDocument.Load(XmlReader reader)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Shared.SolutionConfiguration.GetProjectConfigurations(String xmlString)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Shared.SolutionConfiguration..ctor(String xmlString)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Graph.ProjectInterpretation.<GetReferences>d__24.MoveNext()
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Graph.GraphBuilder.ParseReferences(ProjectGraphNode parsedProject)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at Microsoft.Build.Graph.GraphBuilder.ParseProject(ConfigurationMetadata configurationMetadata)
3>C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.RestoreEx.targets(19,5): error :    at System.Lazy`1.CreateValue()
```

Notes:

1. This **only** repros if you build the solution within VS - building via the CLI still works fine.
2. Our CI currently uses VS 17.5 which is possibly why we haven't seen this yet.
3. The error can be can be worked around by setting `<DisableRestoreUseStaticGraphEvaluation>true</DisableRestoreUseStaticGraphEvaluation>` to prevent the (experimental) static graph evaluation from running.

### Steps To Reproduce

1. Open `Microsoft.ReactNative.sln` in Visual Studio >= 17.6.
2. Build the solution

### Expected Results

Solution builds successfully.

### CLI version

12.0.0-alpha.3

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.25336
  CPU: "(24) x64 AMD Ryzen Threadripper PRO 3945WX 12-Cores     "
  Memory: 54.05 GB / 63.86 GB
Binaries:
  Node:
    version: 16.19.1
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.19
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 9.6.2
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 16.11.33529.622 (Visual Studio Enterprise 2019)
    - 17.6.33723.286 (Visual Studio Enterprise 2022)
    - 17.7.33711.374 (Visual Studio Enterprise 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by jonthysell** [comment]
The actual error appears to be some kind of xml parsing failure - it's reading xml element attributes and seeing a `{` i.e. `<element attribute={` instead of `<element attribute="`. but it's just a stack trace from msbuild so I don't know what input is being parsed. One of our project files? Some intermediate file?

The question is do I do the quick work of disabling this (technically experimental) feature at the potential expense of longer builds, and backport the changes to every supported branch? I've yet to find a malformed file in our repo and I don't have a minimal repro I can push on the VS team.

**Comment by jonthysell** [comment]
The linked PR fixes the build blocker but at the expense of disabling `RestoreUseStaticGraphEvaluation` on VS >= 17.6. Maybe later we'll be able to re-enable it.

FYI @JunielKatarn

**Comment by jonthysell** [comment]
Didn't mean to close it - adding back to triage so we can decide what to do with this.

**Comment by chrisglein** [comment]
Unclear from the error message what it's failing to parse. Might be something we can fix that way? But needs more digging to find out.

In the meantime, we were using an experimental feature to improve build times, and a new VS version broke that experimental behavior, and the impact is that we disable the feature and don't get the improved build times.

**Comment by MaxBen93** [comment]
For what it's worth, doing a bit of digging with a debugger I was able to figure out that the issue seems to be in some generated XML that contains the `<SolutionConfiguration>` and `<ProjectConfiguration>` tags.

Specifically, for us the place where this is failing is because there is someting along the lines of:
```xml
<SolutionConfiguration>
  <ProjectConfiguration Project={GUID-GOES-HERE} AbsolutePath=G:\Path\To\Project.vcxproj>Debug|x64</ProjectConfiguration>
  <!-- and so forth -->
</SolutionConfiguration>
```

Hopefully that should help VS folks hone in on the issue.  @jonthysell / @chrisglein are you actively following-up with them already?

**Comment by MasonBergstrom** [comment]
FYI the react-native-xaml project is running into this exact same issue. Downgrading to 17.5.5 fixed it for me. Potentially another data point to send onto the VS folks.

**Comment by TatianaKapos** [comment]
This doesn't specifically need to be in v73 but we should figure out if we need to reenable this in v74.
