### ISSUE TITLE
yarn integrate-rn script is broken

### ISSUE THREAD

**Issue by TatianaKapos** [microsoft/react-native-windows#11824]
### Problem Description

Integration script worked fine last week but this week it's throwing the following local change error when trying to integrate any commit (even the same rn-version we are currently using). Some of the files listed aren't in our repository. This will halt integrations until it can be fixed :(

```
yarn run v1.22.5
$ D:\react-native-windows\node_modules\.bin\integrate-rn 0.73.0-nightly-20230602-e25c6632a
i Commits: https://github.com/facebook/react-native/compare/v0.73.0-nightly-20230602-e25c6632a...v0.73.0-nightly-20230602-e25c6632a
× Updating packages and dependents to react-native@0.73.0-nightly-20230602-e25c6632a
Error: Failed to fetch 'e25c6632a2360acfb63ceb62258ee1ec18452018'. Does it exist? (error: Your local changes to the following files would be overwritten by checkout:
        .circleci/config.yml
        .eslintrc.js
        .flowconfig
        .flowconfig.android
        .github/workflow-scripts/verifyVersion.js
        .github/workflows/autorebase.yml
        .gitignore
        .prettierrc
        CHANGELOG.md
        README.md
        gradle/wrapper/gradle-wrapper.properties
        jest/preprocessor.js
        package.json
        packages/eslint-config-react-native/package.json
        packages/react-native-codegen-typescript-test/package.json
        packages/react-native-codegen/e2e/__tests__/modules/__snapshots__/GenerateModuleH-test.js.snap
        packages/react-native-codegen/package.json
        packages/react-native-codegen/src/generators/modules/GenerateModuleH.js
        packages/react-native-codegen/src/generators/modules/__tests__/__snapshots__/GenerateModuleH-test.js.snap
        packages/react-native-codegen/src/parsers/__tests__/parsers-commons-test.js
        packages/react-native-codegen/src/parsers/__tests__/parsers-primitives-test.js
        packages/react-native-codegen/src/parsers/__tests__/parsers-test.js
        packages/react-native-codegen/src/parsers/flow/components/componentsUtils.js
        packages/react-native-codegen/src/parsers/flow/components/events.js
        packages/react-native-codegen/src/parsers/flow/components/index.js
        packages/react-native-codegen/src/parsers/flow/parser.js
        packages/react-native-codegen/src/parsers/parser.js
        packages/react-native-codegen/src/parsers/parserMock.js
        packages/react-native-codegen/src/parsers/parsers-commons.js
        packages/react-native-codegen/src/parsers/parsers-primitives.js
        packages/react-native-codegen/src/parsers/typescript/components/componentsUtils.js
        packages/react-native-codegen/src/parsers/typescript/components/events.js
        packages/react-native-codegen/src/parsers/typescript/components/index.js
        packages/react-native-codegen/src/parsers/typescript/modules/index.js
        packages/react-native-codegen/src/parsers/typescript/parser.js
        packages/react-native-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
        packages/react-native/Libraries/Animated/AnimatedImplementation.js
        packages/react-native/Libraries/Animated/NativeAnimatedModule.js
        packages/react-native/Libraries/Animated/NativeAnimatedTurboModule.js
        packages/react-native/Libraries/Animated/__tests__/AnimatedNative-test.js
        packages/react-native/Libraries/Animated/animations/Animation.js
        packages/react-native/Libraries/Animated/animations/DecayAnimation.js
        packages/react-native/Libraries/Animated/animations/SpringAnimation.js
        packages/react-native/Libraries/Animated/animations/TimingAnimation.js
        packages/react-native/Libraries/Animated/nodes/AnimatedValueXY.js
        packages/react-native/Libraries/Animated/useAnimatedProps.js
        packages/react-native/Libraries/AppDelegate/RCTAppDelegate.h
        packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
        packages/react-native/Libraries/AppDelegate/RCTAppSetupUtils.mm
        packages/react-native/Libraries/AppDelegate/React-RCTAppDelegate.podspec
        packages/react-native/Libraries/AppState/AppState.d.ts
        packages/react-native/Libraries/Components/Pressable/useAndroidRippleForView.js
        packages/react-native/Libraries/Components/ScrollView/ScrollViewStickyHeader.js
        packages/react-native/Libraries/Components/TextInput/RCTTextInputViewConfig.js
        packages/react-native/Libraries/Components/TextInput/TextInput.d.ts
        packages/react-native/Libraries/Components/TextInput/TextInput.flow.js
        packages/react-native/Libraries/Components/TextInput/TextInput.js
        packages/react-native/Libraries/Core/setUpPerformance.js
        packages/react-native/Libraries/Core/setUpRegeneratorRuntime.js
        packages/react-native/Libraries/DOM/Nodes/ReactNativeElement.js
        packages/react-native/Libraries/DOM/Nodes/ReadOnlyElement.js
        packages/react-native/Libraries/DOM/Nodes/ReadOnlyNode.js
        packages/react-native/Libraries/Image/RCTImageLoader.h
        packages/react-native/Libraries/Image/RCTImageLoader.mm
        packages/react-native/Libraries/Image/RCTImageStoreManager.h
        packages/react-native/Libraries/Image/RCTImageStoreManager.mm
        packages/react-native/Libraries/Interaction/JSEventLoopWatchdog.js
        packages/react-native/Libraries/LogBox/UI/LogBoxI
Aborting
)
    at GitReactFileRepository.fetchAndCheckout (D:\react-native-windows\packages\react-native-platform-override\src\GitReactFileRepository.ts:224:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at GitReactFileRepository.checkoutVersion (D:\react-native-windows\packages\react-native-platform-override\src\GitReactFileRepository.ts:198:9)
    at D:\react-native-windows\packages\react-native-platform-override\src\GitReactFileRepository.ts:190:7
    at D:\react-native-windows\packages\react-native-platform-override\src\BatchingQueue.ts:24:19
    at BatchingQueue.pumpQueue (D:\react-native-windows\packages\react-native-platform-override\src\BatchingQueue.ts:41:7)

D:\react-native-windows\packages\react-native-platform-override\src\GitReactFileRepository.ts:224
      throw new Error(
            ^
Error: Failed to fetch 'e25c6632a2360acfb63ceb62258ee1ec18452018'. Does it exist? (error: Your local changes to the following files would be overwritten by checkout:
        .circleci/config.yml
        .eslintrc.js
        .flowconfig
        .flowconfig.android
        .github/workflow-scripts/verifyVersion.js
        .github/workflows/autorebase.yml
        .gitignore
        .prettierrc
        CHANGELOG.md
        README.md
        gradle/wrapper/gradle-wrapper.properties
        jest/preprocessor.js
        package.json
        packages/eslint-config-react-native/package.json
        packages/react-native-codegen-typescript-test/package.json
        packages/react-native-codegen/e2e/__tests__/modules/__snapshots__/GenerateModuleH-test.js.snap
        packages/react-native-codegen/package.json
        packages/react-native-codegen/src/generators/modules/GenerateModuleH.js
        packages/react-native-codegen/src/generators/modules/__tests__/__snapshots__/GenerateModuleH-test.js.snap
        packages/react-native-codegen/src/parsers/__tests__/parsers-commons-test.js
        packages/react-native-codegen/src/parsers/__tests__/parsers-primitives-test.js
        packages/react-native-codegen/src/parsers/__tests__/parsers-test.js
        packages/react-native-codegen/src/parsers/flow/components/componentsUtils.js
        packages/react-native-codegen/src/parsers/flow/components/events.js
        packages/react-native-codegen/src/parsers/flow/components/index.js
        packages/react-native-codegen/src/parsers/flow/parser.js
        packages/react-native-codegen/src/parsers/parser.js
        packages/react-native-codegen/src/parsers/parserMock.js
        packages/react-native-codegen/src/parsers/parsers-commons.js
        packages/react-native-codegen/src/parsers/parsers-primitives.js
        packages/react-native-codegen/src/parsers/typescript/components/componentsUtils.js
        packages/react-native-codegen/src/parsers/typescript/components/events.js
        packages/react-native-codegen/src/parsers/typescript/components/index.js
        packages/react-native-codegen/src/parsers/typescript/modules/index.js
        packages/react-native-codegen/src/parsers/typescript/parser.js
        packages/react-native-gradle-plugin/gradle/wrapper/gradle-wrapper.properties
        packages/react-native/Libraries/Animated/AnimatedImplementation.js
        packages/react-native/Libraries/Animated/NativeAnimatedModule.js
        packages/react-native/Libraries/Animated/NativeAnimatedTurboModule.js
        packages/react-native/Libraries/Animated/__tests__/AnimatedNative-test.js
        packages/react-native/Libraries/Animated/animations/Animation.js
        packages/react-native/Libraries/Animated/animations/DecayAnimation.js
        packages/react-native/Libraries/Animated/animations/SpringAnimation.js
        packages/react-native/Libraries/Animated/animations/TimingAnimation.js
        packages/react-native/Libraries/Animated/nodes/AnimatedValueXY.js
        packages/react-native/Libraries/Animated/useAnimatedProps.js
        packages/react-native/Libraries/AppDelegate/RCTAppDelegate.h
        packages/react-native/Libraries/AppDelegate/RCTAppDelegate.mm
        packages/react-native/Libraries/AppDelegate/RCTAppSetupUtils.mm
        packages/react-native/Libraries/AppDelegate/React-RCTAppDelegate.podspec
        packages/react-native/Libraries/AppState/AppState.d.ts
        packages/react-native/Libraries/Components/Pressable/useAndroidRippleForView.js
        packages/react-native/Libraries/Components/ScrollView/ScrollViewStickyHeader.js
        packages/react-native/Libraries/Components/TextInput/RCTTextInputViewConfig.js
        packages/react-native/Libraries/Components/TextInput/TextInput.d.ts
        packages/react-native/Libraries/Components/TextInput/TextInput.flow.js
        packages/react-native/Libraries/Components/TextInput/TextInput.js
        packages/react-native/Libraries/Core/setUpPerformance.js
        packages/react-native/Libraries/Core/setUpRegeneratorRuntime.js
        packages/react-native/Libraries/DOM/Nodes/ReactNativeElement.js
        packages/react-native/Libraries/DOM/Nodes/ReadOnlyElement.js
        packages/react-native/Libraries/DOM/Nodes/ReadOnlyNode.js
        packages/react-native/Libraries/Image/RCTImageLoader.h
        packages/react-native/Libraries/Image/RCTImageLoader.mm
        packages/react-native/Libraries/Image/RCTImageStoreManager.h
        packages/react-native/Libraries/Image/RCTImageStoreManager.mm
        packages/react-native/Libraries/Interaction/JSEventLoopWatchdog.js
        packages/react-native/Libraries/LogBox/UI/LogBoxI
Aborting
)
    at GitReactFileRepository.fetchAndCheckout (D:\react-native-windows\packages\react-native-platform-override\src\GitReactFileRepository.ts:224:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at GitReactFileRepository.checkoutVersion (D:\react-native-windows\packages\react-native-platform-override\src\GitReactFileRepository.ts:198:9)
    at D:\react-native-windows\packages\react-native-platform-override\src\GitReactFileRepository.ts:190:7
    at D:\react-native-windows\packages\react-native-platform-override\src\BatchingQueue.ts:24:19
    at BatchingQueue.pumpQueue (D:\react-native-windows\packages\react-native-platform-override\src\BatchingQueue.ts:41:7)
error Command failed with exit code 1.
```

### Steps To Reproduce

1. Try an integration
2. Script won't work as expected

### Expected Results

script runs fine

### CLI version

0.73.0-nightly-20230601-d9b3339ef

### Environment

```markdown
info Fetching system and libraries information...
System:
  OS: Windows 10 10.0.22621
  CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  Memory: 36.94 GB / 63.85 GB
Binaries:
  Node:
    version: 16.12.0
    path: C:\Program Files\nodejs\node.EXE
  Yarn:
    version: 1.22.5
    path: C:\Program Files (x86)\Yarn\bin\yarn.CMD
  npm:
    version: 8.1.0
    path: C:\Program Files\nodejs\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.17763.0
      - 10.0.18362.0
      - 10.0.19041.0
      - 10.0.22000.0
IDEs:
  Android Studio: AI-213.7172.25.2113.9014738
  Visual Studio:
    - 16.11.33801.447 (Visual Studio Enterprise 2019)
    - 17.6.33801.468 (Visual Studio Enterprise 2022)
Languages:
  Java:
    version: 11.0.16.1
    path: C:\Program Files\Eclipse Adoptium\jdk-11.0.16.101-hotspot\bin\javac.EXE
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

**Comment by TatianaKapos** [comment]
closing, seems to only affect my devBox will update if I find out why :)
