### ISSUE TITLE
XCode still requiring react-native-windows after removing package

### ISSUE THREAD

**Issue by RyanMitchellWilson** [Microsoft/react-native-windows#1284]
I had to install this package because it was a dependency on react-native-video but that caused it's own problems trying to run the ios app. So I removed both dependencies and even recloned my project and now XCode keeps looking for something in `node-modules/react-native-windows`. 
I have a brand new clone of my project without any of the react-native-windows stuff (cloned at the same path), and I'm getting this error.
```
error: bundling: Error: ENOENT: no such file or directory, open '/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Module._readSourceCode (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.ios.js`  90.6% (1321/1388), failed.
Error: ENOENT: no such file or directory, open '/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Module._readSourceCode (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
error: bundling: Error: ENOENT: no such file or directory, open '/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Module._readSourceCode (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.ios.js`  52.5% (866/1195), failed.
Error: ENOENT: no such file or directory, open '/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Module._readSourceCode (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Error: ENOENT: no such file or directory, open '/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native-windows/Libraries/Components/ActivityIndicator/ActivityIndicator.windows.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at Module._readSourceCode (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:200:29)
    at Module._getCacheProps (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:420:29)
    at Module._readFromTransformCache (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:376:29)
    at Module.readCached (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/Module.js:363:25)
    at Promise.resolve.then (/Users/ryanwilson/temp/AthlinksMobile/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:167:29)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

The only way I have found to fix this is to reclone the project into a completely different directory and then it will work correctly. This has basically made my `work` directory unusable. I have been able to reproduce this in two different places on my machine both giving me the exact same error.

Steps to reproduce:
Clone your project into a new directory
Then install react-native-windows
Then try to launch the app in ios (`react-native run-ios`)
This will cause the ios side of your app to break because it keeps replacing `ios.js` files with `windows.js` files. (Bug here: https://github.com/Microsoft/react-native-windows/issues/1255)
Then remove react-native-windows from package.json
Remove node-modules and reinstall
Then run `react-native run-ios`
Now the app will red screen every time with the packager giving these error.

Using:
react-native: 0.44
xcode: 8.3.3
react-native-video: 1.2 which includes react-native-windows: 0.41.0-rc.0

**Comment by rozele** [comment]
@RyanMitchellWilson you need to reset the bundler cache with --reset-cache after removing react-native-windows. As for the issue with *.windows.js files being picked up by the packager for *.ios.js, we should leave #1255 open for that.
