### ISSUE TITLE
Installation failure on Windows 11

### ISSUE THREAD

**Issue by travpeck** [microsoft/react-native-windows#13003]
### Problem Description

```
C:\Users\user1\VsCodeProjects\rnative>npx --yes react-native-windows-init --overwrite

> rnative@0.0.1 npx
> react-native-windows-init --overwrite

Reading project name from package.json...
Reading react-native version from node_modules...
Reading react-native version from node_modules...
Latest matching version of react-native-windows for react-native@0.74.0 is react-native-windows@0.74.0
Installing react-native-windows@0.74.0...
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: rnative@0.0.1
npm error Found: react-native@0.74.0
npm error node_modules/react-native
npm error   react-native@"0.74.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react-native@"0.74.0-rc.9" from react-native-windows@0.74.0
npm error node_modules/react-native-windows
npm error   react-native-windows@"0.74.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\user1\scoop\persist\nodejs-lts\cache\_logs\2024-04-28T19_00_35_817Z-eresolve-report.txt

npm error A complete log of this run can be found in: C:\Users\user1\scoop\persist\nodejs-lts\cache\_logs\2024-04-28T19_00_35_817Z-debug-0.log
Command failed: npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: rnative@0.0.1
npm error Found: react-native@0.74.0
npm error node_modules/react-native
npm error   react-native@"0.74.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react-native@"0.74.0-rc.9" from react-native-windows@0.74.0
npm error node_modules/react-native-windows
npm error   react-native-windows@"0.74.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\user1\scoop\persist\nodejs-lts\cache\_logs\2024-04-28T19_00_35_817Z-eresolve-report.txt

npm error A complete log of this run can be found in: C:\Users\user1\scoop\persist\nodejs-lts\cache\_logs\2024-04-28T19_00_35_817Z-debug-0.log

Error: Command failed: npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: rnative@0.0.1
npm error Found: react-native@0.74.0
npm error node_modules/react-native
npm error   react-native@"0.74.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react-native@"0.74.0-rc.9" from react-native-windows@0.74.0
npm error node_modules/react-native-windows
npm error   react-native-windows@"0.74.0" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\user1\scoop\persist\nodejs-lts\cache\_logs\2024-04-28T19_00_35_817Z-eresolve-report.txt

npm error A complete log of this run can be found in: C:\Users\user1\scoop\persist\nodejs-lts\cache\_logs\2024-04-28T19_00_35_817Z-debug-0.log

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at installReactNativeWindows (C:\Users\user1\scoop\persist\nodejs-lts\cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\src\Cli.ts:319:13)
    at Object.reactNativeWindowsInit (C:\Users\user1\scoop\persist\nodejs-lts\cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\src\Cli.ts:635:5)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 6e 70 6d 20 65 72 72 6f 72 20 63 6f 64 65 20 45 52 45 53 4f 4c 56 45 0a 6e 70 6d 20 65 72 72 6f 72 20 45 52 45 53 4f 4c 56 45 20 75 6e 61 62 6c 65 20 ... 952 more bytes>
  ],
  pid: 9784,
  stdout: <Buffer >,
  stderr: <Buffer 6e 70 6d 20 65 72 72 6f 72 20 63 6f 64 65 20 45 52 45 53 4f 4c 56 45 0a 6e 70 6d 20 65 72 72 6f 72 20 45 52 45 53 4f 4c 56 45 20 75 6e 61 62 6c 65 20 ... 952 more bytes>
}
Command failed. Re-run the command with --verbose for more information.
```

### Steps To Reproduce

1.) Installed the dev dependences.
- For node I used scoop: `scoop install main/nodejs-lts`
- Everything else I used: `rnw-dependencies.ps1`

2.) `npx --yes react-native@latest init <projectName> --version "latest"`
3.) `cd projectName`
4.) `npx --yes react-native-windows-init --overwrite`

And received error in description.

### Expected Results

Installation of the Windows extension.

### CLI version

npx react-native -v

### Environment

```markdown
npx react-native info
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

None

**Comment by travpeck** [comment]
Okay, so it looks like Yarn is required in order to install/use react-native-window.

The documentation however says that Yarn is optional (and only for contributing).

**Comment by Doug233** [comment]
You need to use a specific version, because RN-windows 0.74 have not be release, they can't always follow RN upstream.
`npx --yes react-native@0.73 init <projectName> --version 0.73`

**Comment by chrisglein** [comment]
> You need to use a specific version, because RN-windows 0.74 have not be release, they can't always follow RN upstream. `npx --yes react-native@0.73 init <projectName> --version 0.73`

You _just_ caught the bump from 73 to 74, which released... today! https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.74.0
Can you try again with the landed 0.74.0 now that you don't need canary?

**Comment by travpeck** [comment]
> > You need to use a specific version, because RN-windows 0.74 have not be release, they can't always follow RN upstream. `npx --yes react-native@0.73 init <projectName> --version 0.73`
> 
> You _just_ caught the bump from 73 to 74, which released... today! https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.74.0 Can you try again with the landed 0.74.0 now that you don't need canary?

This must have been it. Everything works now.
