### ISSUE TITLE
Unable to run app due to unsupported param type being passed to DebuggingOverlayNativeComponent.js

### ISSUE THREAD

**Issue by shirakaba** [microsoft/react-native-windows#13482]
### Problem Description

Sorry for the slim details, as this is a closed-source project and I'm integrating into a monorepo with some best-effort Expo integration, but just hoping someone has seen this stack before and knows what it's about. It seems to be an error entirely internal to React Native Windows, so I'm not sure whether the userland code matters.

This error occurs the moment my app starts up, and dismissing it leaves me with a screen in an error state. The error stack is:

```
..\..\node_modules\react-native-windows\src\private\specs\components\DebuggingOverlayNativeComponent.js: C:\Users\jamie\git\banana_native\node_modules\react-native-windows\src\private\specs\components\DebuggingOverlayNativeComponent.js: Unsupported param type for method "highlightTraceUpdates", param "updates". Found $ReadOnlyArray

    at C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\flow\components\commands.js:77:15
    at Array.map (<anonymous>)
    at buildCommandSchema (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\flow\components\commands.js:35:40)
    at C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\flow\components\commands.js:102:22
    at Array.map (<anonymous>)
    at getCommands (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\flow\components\commands.js:102:6)
    at buildComponentSchema (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\flow\components\index.js:36:20)
    at buildSchemaFromConfigType (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\parsers-commons.js:462:34)
    at buildSchema (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\parsers-commons.js:526:10)
    at FlowParser.parseString (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\codegen\lib\parsers\flow\parser.js:134:12)
    at parseFile (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\babel-plugin-codegen\index.js:36:23)
    at generateViewConfig (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\babel-plugin-codegen\index.js:49:18)
    at PluginPass.exit (C:\Users\jamie\git\banana_native\node_modules\babel-preset-expo\node_modules\@react-native\babel-plugin-codegen\index.js:169:32)
    at newFn (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\visitors.js:160:14)
    at NodePath._call (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\path\context.js:46:20)
    at NodePath.call (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\path\context.js:36:17)
    at NodePath.visit (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\path\context.js:90:8)
    at TraversalContext.visitQueue (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\context.js:89:16)
    at TraversalContext.visitSingle (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\context.js:65:19)
    at TraversalContext.visit (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\context.js:112:19)
    at traverseNode (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\traverse-node.js:22:17)
    at traverse (C:\Users\jamie\git\banana_native\node_modules\@babel\traverse\lib\index.js:52:34)
    at transformFile (C:\Users\jamie\git\banana_native\node_modules\@babel\core\lib\transformation\index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (C:\Users\jamie\git\banana_native\node_modules\@babel\core\lib\transformation\index.js:24:12)
    at run.next (<anonymous>)
    at transform (C:\Users\jamie\git\banana_native\node_modules\@babel\core\lib\transform.js:22:33)
    at transform.next (<anonymous>)
    at evaluateSync (C:\Users\jamie\git\banana_native\node_modules\gensync\index.js:251:28)
    at sync (C:\Users\jamie\git\banana_native\node_modules\gensync\index.js:89:14)
    at stopHiding - secret - don't use this - v1 (C:\Users\jamie\git\banana_native\node_modules\@babel\core\lib\errors\rewrite-stack-trace.js:47:12)
    at Object.transformSync (C:\Users\jamie\git\banana_native\node_modules\@babel\core\lib\transform.js:42:76)
    at parseWithBabel (C:\Users\jamie\git\banana_native\node_modules\@expo\metro-config\build\transformSync.js:57:18)
    at transformSync (C:\Users\jamie\git\banana_native\node_modules\@expo\metro-config\build\transformSync.js:46:12)
    at Object.transform (C:\Users\jamie\git\banana_native\node_modules\@expo\metro-config\build\babel-transformer.js:108:58)
    at module.exports.transform (C:\Users\jamie\git\banana_native\node_modules\react-native-svg-transformer\index.js:58:30)
    at transformJSWithBabel (C:\Users\jamie\git\banana_native\node_modules\@expo\metro-config\build\transform-worker\metro-transform-worker.js:304:47)
    at Object.transform (C:\Users\jamie\git\banana_native\node_modules\@expo\metro-config\build\transform-worker\metro-transform-worker.js:407:12)
    at Object.transform (C:\Users\jamie\git\banana_native\node_modules\@expo\metro-config\build\transform-worker\transform-worker.js:68:23)
    at transformFile (C:\Users\jamie\git\banana_native\node_modules\metro\src\DeltaBundler\Worker.flow.js:54:36)
    at Object.transform (C:\Users\jamie\git\banana_native\node_modules\metro\src\DeltaBundler\Worker.flow.js:30:10)
    at execFunction (C:\Users\jamie\git\banana_native\node_modules\jest-worker\build\workers\processChild.js:149:17)
    at execHelper (C:\Users\jamie\git\banana_native\node_modules\jest-worker\build\workers\processChild.js:137:5)
    at execMethod (C:\Users\jamie\git\banana_native\node_modules\jest-worker\build\workers\processChild.js:140:5)
    at process.messageListener (C:\Users\jamie\git\banana_native\node_modules\jest-worker\build\workers\processChild.js:44:7)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
```

I can see that `babel-preset-expo` appears throughout the stack trace, so when I have a free moment, I'll check whether my usage of that is the whole cause of the problem, as the config that comes with the template is rather:

```diff
  module.exports = (api) => {
    api.cache(true);
    return {
-     presets: ["babel-preset-expo"],
+     presets: ['module:@react-native/babel-preset'],
    };
  };
```

### Steps To Reproduce

I created a new app from the template, then integrated it into my pnpm monorepo (which involves Expo), built it, and tried to run it.

### Expected Results

No error on startup.

### CLI version

13.6.9

### Environment

```markdown
$ pnpm exec react-native info
info Fetching system and libraries information...
System:
  OS: Windows 11 10.0.22631
  CPU: (4) x64 Apple Silicon
  Memory: 1.03 GB / 7.99 GB
Binaries:
  Node:
    version: 20.15.0
    path: ~\AppData\Local\Volta\tools\image\node\20.15.0\node.EXE
  Yarn: Not Found
  npm:
    version: 10.7.0
    path: ~\AppData\Local\Volta\tools\image\node\20.15.0\npm.CMD
  Watchman: Not Found
SDKs:
  Android SDK: Not Found
  Windows SDK:
    AllowDevelopmentWithoutDevLicense: Enabled
    AllowAllTrustedApps: Enabled
    Versions:
      - 10.0.19041.0
      - 10.0.22621.0
IDEs:
  Android Studio: Not Found
  Visual Studio:
    - 17.10.35027.167 (Visual Studio Community 2022)
Languages:
  Java: Not Found
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-windows: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Community Modules

Full package.json:

```json
{
  "name": "@org/banana-native",
  "version": "1.0.0",
  "main": "src/index.js",
  "dependencies": {
    "class-variance-authority": "^0.7.0",
    "expo": "~50.0.18",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-app-auth": "^7.2.0",
    "react-native-macos": "~0.73.30",
    "react-native-outside-press": "^1.2.2",
    "react-native-svg": "15.4.0",
    "react-native-windows": "0.74.11",
    "tailwind-merge": "^2.4.0",
    "typescript": "^5.5.3"
  },
  "devDependencies": {
    "@babel/core": "^7.22.11",
    "@biomejs/biome": "1.8.3",
    "@types/react": "~18.3.3",
    "react-native-svg-transformer": "^1.4.0",
    "tailwindcss": "3.3.2"
  },
  "scripts": {
    "dev": "expo start --dev-client",
    "start": "expo start --dev-client",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "build": "expo export --output-dir ./build --platform all",
    "macos": "echo \"Expo CLI doesn't support macOS fully, so start a packager (if you haven't already) with `pnpm start`, then open macos/noman.xcworkspace and run the \"noman-macOS\" target to run the macOS app.\"",
    "windows": "react-native run-windows --logging --arch arm64",
    "eas-build-post-install": "pnpm run -w build:mobile",
    "format": "biome format",
    "lint": "biome lint"
  },
  "private": true
}
```

### Target Platform Version

None

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2022

### Build Configuration

Debug

### Snack, code example, screenshot, or link to a repository

Closed-source, unfortunately!

**Comment by acoates-ms** [comment]
I'd also verify that none of the react-native 0.73 related versions from the rn-macos dependency are getting used - maybe try removing that dependency and verify that all the babel/codegen packages in your lock file are from 0.74.

Also verify what versions of those dependencies babel-preset-expo uses.

Maybe look at the version of rn/codegen being used from expo's preset and verify it aligns with the version used by RNW?
We are certainly able to run the rn/codegen on DebuggingOverlayNativeComponent.js in our loops.

**Comment by chrisglein** [comment]
Investigate those config issues to see what's drifted from the golden path and let us know if that doesn't shake it out.

**Comment by Yajur-Grover** [comment]
Hit this same issue when trying to bump async-storage from 0.73 to 0.74. For me, bumping my version of `@react-native/babel-preset` to match the version of `react-native` that I was upgrading to resolved the issue for me.

**Comment by sugaith** [comment]
I am having the same In a monorepo
