### ISSUE TITLE
I receive the following error when trying to run react-native-windows error: bundling failed: \babel-preset-react-native\\index.js

### ISSUE THREAD

**Issue by xtianus79** [microsoft/react-native-windows#1962]
### Environment

1. `react-native -v`: .55
2. `npm ls rnpm-plugin-windows`: latest
3. `npm ls react-native-windows`: latest
4. `node -v`: 8.11.3
5. `npm -v`: cooresponding
6. `yarn --version`:

Then, specify:

- Target Platform:

UWP

Windows 10... 

I get this error for bable when trying to run the platform... 

Loading dependency graph, done.
error: bundling failed: Error: Plugin 0 specified in "C:\\repos\\helloworld\\node_modules\\babel-preset-react-native\\index.js" provided an invalid property of "default" (While processing preset: "C:\\repos\\helloworld\\node_modules\\babel-preset-react-native\\index.js")
    at Plugin.init (C:\repos\helloworld\node_modules\babel-core\lib\transformation\plugin.js:131:13)
    at Function.normalisePlugin (C:\repos\helloworld\node_modules\babel-core\lib\transformation\file\options\option-manager.js:152:12)
    at C:\repos\helloworld\node_modules\babel-core\lib\transformation\file\options\option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (C:\repos\helloworld\node_modules\babel-core\lib\transformation\file\options\option-manager.js:158:20)
    at OptionManager.mergeOptions (C:\repos\helloworld\node_modules\babel-core\lib\transformation\file\options\option-manager.js:234:36)
    at C:\repos\helloworld\node_modules\babel-core\lib\transformation\file\options\option-manager.js:265:14
    at C:\repos\helloworld\node_modules\babel-core\lib\transformation\file\options\option-manager.js:323:22
    at Array.map (<anonymous>)
 BUNDLE  [windows, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

**Comment by rozele** [comment]
Does this still repro react-native-windows@0.55? Can you try v0.57?
