### ISSUE TITLE
CI Loop instability:  Build and Pack NuGet randomly fails

### ISSUE THREAD

**Issue by kmelmon** [microsoft/react-native-windows#3444]
I've been seeing a random failure in our CI loops that has nothing to do with the changes being checked in.  As an example see:

https://github.com/microsoft/react-native-windows/pull/3442/checks?check_run_id=263149160

Failure occurs during Build and Pack Nuget pipeline.
The failure log looks like this:

The nuget command failed with exit code(1) and error(Could not find a part of the path 'd:\a\1\s\ReactWindows\x64\Debug\React.Windows.Desktop.DLL'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'd:\a\1\s\ReactWindows\x64\Debug\React.Windows.Desktop.DLL'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath)
   at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories)
   at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
   at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider)
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories, Boolean deterministic)
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildPackage()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args))

**Comment by acoates-ms** [comment]
The failure in that run was that one of the slices timed-out. -- Looks like the integration tests timed-out.

@JunielKatarn , I wonder if this is related to the Start-TestServers.ps1 script.  Seems like we should really make this script do something other than a sleep to determine that the server is ready.  -- I think at one point it was recording the output of the bundler and waiting for it to say ready.

Or maybe at least have it poll the server a few times... so that increasing the timeout doesn't slow down every run.

**Comment by JunielKatarn** [comment]
@acoates-ms I don't think this is the case. Integration test `Dummy` passed, which requires the bundler to be ready.

Unfortunately, VSTest has currently no way to print the test name before it starts running, so it's hard to tell which one is the culprit.
I'll re-run that failed task and see if this was a temporary glitch.

That said, we should address your suggestions and make the start-testservers script more robust.

**Comment by chrisglein** [comment]
@licanhua Can you check in with this and see if the reliability issue is fixed with the above? Sounds like Andrew has some suggestions.

**Comment by licanhua** [comment]
IntegrationTestHarness is one of the non stable test case and I disabled it in #3492, need to re-enable it

**Comment by licanhua** [comment]
Desktop Debug flavor is disabled on pipeline
