### ISSUE TITLE
Error: bundling failed: Error: Unable to resolve module `./$.html` from `E:\React\demo\node_modules\core-js\modules\es5.js

### ISSUE THREAD

**Issue by srikanthsunkari** [microsoft/react-native-windows#4928]
While I am trying run react-native code in microsoft windows environment, facing below issue obviously this is because of the modules are not available available in windows environment.      

``
error: bundling failed: Error: Unable to resolve module `./$.html` from `E:\React\demo\node_modules\core-js\modules\es5.js`: The module `./$.html` could not be found from `E:\React\demo\node_modules\core-js\modules\es5.js`. Indeed, none of these files exist:   * `$.html`   * `E:\React\demo\node_modules\core-js\modules\$.html\index(.native||.windows.jsx|.native.jsx|.jsx|.windows.js|.native.js|.js|.windows.ts|.native.ts|.ts|.windows.json|.native.json|.json)`         at ModuleResolver.resolveDependency (E:\React\demo\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:163:15)         at ResolutionRequest.resolveDependency (E:\React\demo\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:52:18)         at DependencyGraph.resolveDependency (E:\React\demo\node_modules\metro\src\node-haste\DependencyGraph.js:283:16)         at Object.resolve (E:\React\demo\node_modules\metro\src\lib\transformHelpers.js:264:42)         at dependencies.map.result (E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:399:31)         at Array.map (<anonymous>)         at resolveDependencies (E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:18)         at E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:269:33         at Generator.next (<anonymous>)         at asyncGeneratorStep (E:\React\demo\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24) BUNDLE  [windows, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓▓▓▓░░░ 81.3% (1203/1334), failed. 
``

It would be helpful to understand this error exact reason in detail. Could any one please help with this to understand the issue?

**Comment by srikanthsunkari** [comment]
Below are the required version details;

1. react-native -v:
```
react-native-cli: 2.0.1
react-native: 0.60.0

```

2. react-native run-windows --info:

```
System:
    OS: Windows 10 10.0.17763
    CPU: (2) x64 Intel(R) Celeron(R) CPU  N2810  @ 2.00GHz
    Memory: 1.26 GB / 3.90 GB
  Binaries:
    Node: 10.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Users\srikanth\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: ^0.60.0-0 => 0.60.0
    react-native-windows: ^0.60.0-vnext.157 => 0.60.0-vnext.157
    rnpm-plugin-windows: ^0.6.1 => 0.6.1
  Installed UWP SDKs:
    10.0.18362.0

```
Thank you.
