### ISSUE TITLE
Not able to create a react native windows project

### ISSUE THREAD

**Issue by manohargss** [microsoft/react-native-windows#5990]
I started with the link:
https://microsoft.github.io/react-native-windows/docs/getting-started

I ran 1) npx react-native init <projectName> --template react-native@^0.63.2
then I ran 2) browsed to the created folder and then npx react-native-windows-init --overwrite

I am getting the below error:

[Error]
  No compatible version of react-native-windows found.
  The latest supported version is react-native-windows@0.63.1.
  Please modify your application to use react-native@^0.63 or another supported version of react-native and try again.

**Comment by asklar** [comment]
The code that's throwing the error is at https://github.com/microsoft/react-native-windows/blob/c7a42af99fb614652d446ebaee12ea689ade4458/packages/react-native-windows-init/src/Cli.ts#L422

Since we can't reproduce the issue on our end, your best bet is to debug the code yourself (run yarn build to compile this to JavaScript which puts cli.js in the lib-commonjs folder). You can use an IDE like vscode to set breakpoints and step through the code to figure out where things are going wrong for you

**Comment by Jack-Works** [comment]
I got the same problem

Node 15.3.0
npm 7.0.14
yarn 1.22.10

Reproduce:


```shell
npx react-native@latest init rnwin --template react-native-template-typescript@6.5.*
cd rnwin
npx react-native-windows-init --overwrite
```

Failed:

```
Reading project name from package.json...
Reading react-native version from node_modules...

  No compatible version of react-native-windows found.
  The latest supported version is react-native-windows@0.63.14.
  Please modify your application to use react-native@^0.63 or another supported version of react-native and try again.

UserError:
  No compatible version of react-native-windows found.
  The latest supported version is react-native-windows@0.63.14.
  Please modify your application to use react-native@^0.63 or another supported version of react-native and try again.

    at userError (C:\Users\Jack\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\lib-commonjs\Cli.js:328:11)
    at C:\Users\Jack\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\lib-commonjs\Cli.js:370:21
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  exitCode: 'NO_AUTO_MATCHING_RNW'
}
```

➜ yarn why react-native
=> Found "react-native@0.63.4"

**Comment by reutopiaer** [comment]
> I got the same problem
> 
> Node 15.3.0
> npm 7.0.14
> yarn 1.22.10
> 
> Reproduce:
> 
> ```shell
> npx react-native@latest init rnwin --template react-native-template-typescript@6.5.*
> cd rnwin
> npx react-native-windows-init --overwrite
> ```
> 
> Failed:
> 
> ```
> Reading project name from package.json...
> Reading react-native version from node_modules...
> 
>   No compatible version of react-native-windows found.
>   The latest supported version is react-native-windows@0.63.14.
>   Please modify your application to use react-native@^0.63 or another supported version of react-native and try again.
> 
> UserError:
>   No compatible version of react-native-windows found.
>   The latest supported version is react-native-windows@0.63.14.
>   Please modify your application to use react-native@^0.63 or another supported version of react-native and try again.
> 
>     at userError (C:\Users\Jack\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\lib-commonjs\Cli.js:328:11)
>     at C:\Users\Jack\AppData\Local\npm-cache\_npx\966c6a96be6f5a32\node_modules\react-native-windows-init\lib-commonjs\Cli.js:370:21
>     at processTicksAndRejections (node:internal/process/task_queues:93:5) {
>   exitCode: 'NO_AUTO_MATCHING_RNW'
> }
> ```
> 
> ➜ yarn why react-native
> => Found "react-native@0.63.4"

yarn add react-native@0.63.3
