### ISSUE TITLE
Failure to Publish NuGet Package Due to Folly Headers

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6212]
We've been unable to publish binaries since the Folly update.

```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\1\s\ReactWindows\inc\folly'.
Attempting to build package from 'OfficeReact.Win32.nuspec'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath)
   at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories)
   at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
   at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider)
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories, Boolean deterministic)
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.RunPackageBuild()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args)
##[error]The nuget command failed with exit code(1) and error(Could not find a part of the path 'D:\a\1\s\ReactWindows\inc\folly'.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\a\1\s\ReactWindows\inc\folly'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at NuGet.Common.PathResolver.PerformWildcardSearch(String basePath, String searchPath, Boolean includeEmptyDirectories, String& normalizedBasePath)
   at NuGet.Packaging.PackageBuilder.ResolveSearchPattern(String basePath, String searchPath, String targetPath, Boolean includeEmptyDirectories)
   at NuGet.Packaging.PackageBuilder.AddFiles(String basePath, String source, String destination, String exclude)
   at NuGet.Packaging.PackageBuilder.PopulateFiles(String basePath, IEnumerable`1 files)
   at NuGet.Packaging.PackageBuilder.ReadManifest(Stream stream, String basePath, Func`2 propertyProvider)
   at NuGet.Packaging.PackageBuilder..ctor(String path, String basePath, Func`2 propertyProvider, Boolean includeEmptyDirectories, Boolean deterministic)
   at NuGet.Commands.PackCommandRunner.CreatePackageBuilderFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.BuildFromNuspec(String path)
   at NuGet.Commands.PackCommandRunner.RunPackageBuild()
   at NuGet.CommandLine.PackCommand.ExecuteCommand()
   at NuGet.CommandLine.Command.ExecuteCommandAsync()
   at NuGet.CommandLine.Command.Execute()
   at NuGet.CommandLine.Program.MainCore(String workingDirectory, String[] args))
##[error]An error occurred while trying to pack the files.
```

**Comment by chrisglein** [comment]
Passing in CI, but this is failing in publish. Are we missing coverage of that?
Latest update to Folly was a fix that @asklar made, can you look into this failure and maybe start a conversation on how we can better cover publish?

**Comment by asklar** [comment]
I'm not familiar with the nuget package that Office consumes or how it's built, but I believe @NickGerleman is familiar with it. 
Nick, could you add coverage for this in the RNW CI based on how Office consumes it and what files it consumes so that we don't break Office, and also fix the Office script? Thanks!

**Comment by NickGerleman** [comment]
It's the same script as we run for MSRN binaries. If you need context on what's happening, you can take a look at the publish pipeline.

**Comment by jonthysell** [comment]
The issue is with this task: https://github.com/microsoft/react-native-windows/blob/16cf6df4b87022ba31fda2704004c6d15fa40a51/.ado/templates/publish-build-artifacts-for-nuget.yml#L8

It runs a [ps1 script](https://github.com/microsoft/react-native-windows/blob/master/vnext/Scripts/Tfs/Layout-Headers.ps1) to copy the headers to the build artifacts, which then get added to the office nuget. It gets run when layoutHeaders = true, which happens to be during the Universal x64 debug run.

As you can see,[ the script runs](https://dev.azure.com/ms/8d8e50dd-c5b4-4b44-8668-86558c5aa5b7/_apis/build/builds/114852/logs/340) but doesn't copy anything:

```
17935 2020-10-09T05:36:37.4212386Z ##[section]Starting: Copy NuGet header files
17936 2020-10-09T05:36:37.4345783Z ==============================================================================
17937 2020-10-09T05:36:37.4346487Z Task         : PowerShell
17938 2020-10-09T05:36:37.4347081Z Description  : Run a PowerShell script on Linux, macOS, or Windows
17939 2020-10-09T05:36:37.4347471Z Version      : 2.170.1
17940 2020-10-09T05:36:37.4347824Z Author       : Microsoft Corporation
17941 2020-10-09T05:36:37.4348269Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
17942 2020-10-09T05:36:37.4348763Z ==============================================================================
17943 2020-10-09T05:36:38.9207847Z Generating script.
17944 2020-10-09T05:36:38.9272227Z Formatted command: . 'D:\a\1\s\vnext\Scripts\Tfs\Layout-Headers.ps1' -TargetRoot D:\a\1\a
17945 2020-10-09T05:36:38.9783147Z ========================== Starting Command Output ===========================
17946 2020-10-09T05:36:39.0186842Z ##[command]"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". 'D:\a\_temp\1165d295-f912-41bc-9b2f-cb08313db1cd.ps1'"
17947 2020-10-09T05:36:40.2925955Z Source root: [D:\a\1\s]
17948 2020-10-09T05:36:40.2936562Z Destination root: [D:\a\1\a]
17949 2020-10-09T05:36:40.2963549Z React Native root: [C:\agents\2.175.2\BaseIntDir\Common\react-native-patched]
17950 2020-10-09T05:36:41.4400534Z ##[section]Finishing: Copy NuGet header files
```

Besides fixing the script, we should probably stop running it as a part of thje universal build and instead run it during the desktop build, so we don't have this unecessary dependency between them (say if we create separate universal/desktop publish pipielines in the future).
