### ISSUE TITLE
macOS Tests Fail During "yarn install" Trying to Build Detox

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#6353]
We run tests against macOS for react-native-platform-override (and potentially some other code soon), and include Detox as an available package by virtue of keeping a copy of RN Core's `repo-config` package in our repo. As of this morning, a CI change seems to mean Detox fails to build, without much of an error message quite yet.

We should consider forking `repo-config` to remove packages we don't need, but for now, I've turned off macOS tests to unblock merging.

```
[5/5] Building fresh packages...
error /Users/runner/work/1/s/node_modules/detox: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /Users/runner/work/1/s/node_modules/detox
Output:
Extracting Detox sources...
Building Detox.framework from /Users/runner/work/1/s/node_modules/detox/ios_src...
child_process.js:656
    throw err;
    ^

Error: Command failed: /Users/runner/work/1/s/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:635:11)
    at Object.execFileSync (child_process.js:653:15)
    at Object.<anonymous> (/Users/runner/work/1/s/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  status: 65,
  signal: null,
  output: [ null, null, null ],
  pid: 1909,
  stdout: null,
  stderr: null
}
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by exotexot** [comment]
This may be due to an outdated detox dependency. 

See https://github.com/wix/Detox/issues/2389
