### ISSUE TITLE
Unhandled XAML exception at runtine when trying to create new C# app using nugets

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#7764]
Exception:

```
Could not find Windows Runtime type 'Microsoft.UI.Xaml.Markup.ReflectionXamlMetadataProvider'.
  at canarynuget.canarynuget_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(String typeName) in C:\code\canarynuget\windows\canarynuget\obj\x86\Debug\XamlTypeInfo.g.cs:line 137
   at canarynuget.canarynuget_XamlTypeInfo.XamlMetaDataProvider.GetXamlType(String fullName) in C:\code\canarynuget\windows\canarynuget\obj\x86\Debug\XamlTypeInfo.g.cs:line 100
   at canarynuget.App.GetXamlType(String fullName) in C:\code\canarynuget\windows\canarynuget\obj\x86\Debug\XamlTypeInfo.g.cs:line 49
```

## Environment
Run the following in your terminal and copy the results here.
1. `npx react-native --version`: 5.0.1-alpha.2
2. `npx react-native info`:

```
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.21376
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Memory: 3.89 GB / 15.84 GB
  Binaries:
    Node: 12.9.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.9.31205.134 (Visual Studio Enterprise 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.0.0-5127c71d6 => 0.0.0-5127c71d6
    react-native-windows: canary => 0.0.0-canary.308
  npmGlobalPackages:
    *react-native*: Not Found
```

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Create new app `npx react-native init canarynuget --version 0.0.0-5127c71d6`
2. Add rnw with `npx react-native-windows-init --language cs --overwrite --experimentalNuGetDependency --version canary`
3. Run app with `npx react-native run-windows`

## Expected Results
App starts

## Snack, code example, screenshot, or link to a repository:
Please provide a Snack (https://snack.expo.io/), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by jonthysell** [comment]
I've confirmed that this doesn't occur when building a new app against M.RN source.

**Comment by jonthysell** [comment]
The type XAML can't find is `Microsoft.ReactNative.ReactApplicationExtension`.

**Comment by chrisglein** [comment]
There are currently some known issues with new C# UWP apps. Will be fixed with 16.10, can be manually worked around today. Don't know if that is related to this at all.

**Comment by jonthysell** [comment]
We've got a fix/workaround we're exploring.
