### ISSUE TITLE
Failing InteropCSModuleTests Against X64 Hermes Release

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#7808]
We see the following three failures running integration-test-app against release Hermes x64. 

```
 ● InteropCSModuleTests › PointConstant

    expected undefined to equal 10, js engine: hermes

      at o(index.windows:426:504),
      at anonymous(index.windows:458:1565),
      at anonymous(index.windows:462:501),
      at anonymous(index.windows:469:419),
      at anonymous(index.windows:464:1343),
      at p(index.windows:80:587),
      at anonymous(index.windows:80:1890),
      at anonymous(index.windows:80:1013),
      at p(index.windows:80:587),
      at o(index.windows:80:1066),
      at anonymous(index.windows:80:1423),
      at tryCallTwo(InternalBytecode.js:61:8),
      at doResolve(InternalBytecode.js:216:24),
      at Promise(InternalBytecode.js:82:13),
      at u(index.windows:80:1407),
      at anonymous(index.windows:80:1459),
      at anonymous(index.windows:80:1013),
      at anonymous(index.windows:80:3848),
      at anonymous(index.windows:464:1276),
      at Xa(index.windows:56:83166),
      at anonymous(index.windows:178:3838),
      at ct(index.windows:56:25986),
      at Wa(index.windows:56:82558),
      at anonymous(index.windows:56:82470),
      at Y(index.windows:178:2883),
      at e(index.windows:178:400),
      at anonymous(index.windows:82:1230),
      at T(index.windows:82:486),
      at callTimers(index.windows:82:2589),
      at value(index.windows:37:3469),
      at anonymous(index.windows:37:662),
      at value(index.windows:37:2459),
      at value(index.windows:37:634)

  ● InteropCSModuleTests › DeltaPoint

    expected undefined to equal 9, js engine: hermes

      at o(index.windows:426:504),
      at anonymous(index.windows:458:1565),
      at anonymous(index.windows:462:501),
      at anonymous(index.windows:469:2329),
      at value(index.windows:37:3763),
      at anonymous(index.windows:37:817),
      at value(index.windows:37:2459),
      at value(index.windows:37:787)

  ● InteropCSModuleTests › DeltaPointAsync

    expected undefined to equal 9, js engine: hermes

      at o(index.windows:426:504),
      at anonymous(index.windows:458:1565),
      at anonymous(index.windows:462:501),
      at anonymous(index.windows:469:2619),
      at p(index.windows:80:587),
      at anonymous(index.windows:80:1890),
      at anonymous(index.windows:80:1013),
      at p(index.windows:80:587),
      at o(index.windows:80:1066),
      at anonymous(index.windows:80:1209),
      at tryCallOne(InternalBytecode.js:53:15),
      at anonymous(InternalBytecode.js:139:26),
      at anonymous(index.windows:82:1632),
      at T(index.windows:82:486),
      at w(index.windows:82:884),
      at callImmediates(index.windows:82:2979),
      at value(index.windows:37:2779),
      at anonymous(index.windows:37:937),
      at value(index.windows:37:2459),
      at value(index.windows:37:907),
      at value(index.windows:37:842)
```

**Comment by NickGerleman** [comment]
Note that they may also be present on Hermes-debug, or Chakra-release. Our past matrix was just web debugging.

**Comment by chrisglein** [comment]
@dannyvv do you have any context on this?

**Comment by NickGerleman** [comment]
The test was disabled to unblock other automation. Likely still active.

**Comment by dannyvv** [comment]
This test is important. It tests native interop between CS modules and the JS side.
It seems that there is a bug on Hermes where it is not serializing objects between a C# native model and hermes....

**Comment by dannyvv** [comment]
I'm swamped with 3 other high priority work items so I don't have time for it this week.
Note if I don't respond to GH, please IM me. GH's email firehose is hard to filter properly.....
