### ISSUE TITLE
Error: Cannot find module 'react-native-windows-init\bin.js' when creating new RNW project

### ISSUE THREAD

**Issue by BartoszKlonowski** [microsoft/react-native-windows#8718]
### Problem Description

When creating a very new project I get the following error:
```
PS C:\Dev\ReproProjects\RNWReproApp> npx react-native-windows-init --overwrite
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'C:\Users\Bartosz\AppData\Local\Yarn\Data\link\react-native-windows-init\bin.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

I've tried to install the @react-native-community/cli locally for this project, but it didn't resolve this error.

I've also tested it with specifying the version of react-native template with `@^0.65.0` just like in the official RNW docs, but the result is the same.

---

My package.json after creating the clean react-native project is:
```json
{
  "name": "rnwreproapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "17.0.2",
    "react-native": "0.65.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/cli": "^5.0.1",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.66.0",
    "react-native-codegen": "^0.0.7",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

### Steps To Reproduce

1. Create the new *react-native* project with all default options:
`npx react-native init RNWReproApp`
2. Initialize the RNW project in it:
`cd RNWReproApp; npx react-native-windows-init --overwrite`

### Expected Results

New /windows directory should be successfully created.

### CLI version

6.0.1

### Environment

```markdown
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 12.82 GB / 23.76 GB
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.21.1 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3
      System Images: android-29 | Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.15063.0, 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Version  4.2.0.0 AI-202.7660.26.42.7486908
    Visual Studio: 16.11.31624.102 (Visual Studio Community 2019), 16.9.30914.41 (Visual Studio Community 2019)
  Languages:
    Java: 1.8.0_292 - C:\Program Files\OpenJDK\openjdk-8u292-b10\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: ^5.0.1 => 5.0.1
    react: 17.0.2 => 17.0.2
    react-native: 0.65.1 => 0.65.1
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Platform Version

10.0.19041

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

**Comment by asklar** [comment]
I suspect this is an issue due to npm 7
Also related: #8654

**Comment by NickGerleman** [comment]
`Error: Cannot find module 'C:\Users\Bartosz\AppData\Local\Yarn\Data\link\react-native-windows-init\bin.js'`

It looks like you've previously linked a locally built version of `react-native-windows-init`. Can you unlink it, or add `--ignore-existing` to pull in a freshly published copy?

**Comment by BartoszKlonowski** [comment]
@NickGerleman I thought the same, but there's nothing to unlink when I try to unlink it. Moreover, I've removed the directory of `react-native-windows-init` so I can't unlink it in it's original place.
I thought that removing the cache dir of yarn would solve that but no...

`--ignore-existing`  <-  I thought the same, but I got the notification of this option being depracated (see microsoft/react-native-windows-samples#555)

**Comment by NickGerleman** [comment]
Smh, I didn't know npm 7 removed that functionality...

Could you remove the following directory? `'C:\Users\Bartosz\AppData\Local\Yarn\Data\link\react-native-windows-init\`

**Comment by BartoszKlonowski** [comment]
That's the thing - It's not there:
```
PS C:\Dev\Projects> dir C:\Users\Bartosz\AppData\Local\Yarn\Data\link

    Directory: C:\Users\Bartosz\AppData\Local\Yarn\Data\link

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        23.09.2021     18:01                @react-native-windows
d----l        18.08.2021     21:44                react-native-windows-hello

PS C:\Dev\Projects> dir C:\Users\Bartosz\AppData\Local\Yarn\Data\link\@react-native-windows\
PS C:\Dev\Projects>
```
I'm aware that this something unusual, so thank you for taking a look @NickGerleman 👍

---

@asklar Can you elaborate on why these can be related?

**Comment by NickGerleman** [comment]
I think global npm bin scripts has a stale reference to your yarn link directory. You could do a goose chase to figure out where npm is grabbing it from, or you could consider just linking a new copy, then unlinking it cleanly.

**Comment by BartoszKlonowski** [comment]
> I think global npm bin scripts has a stale reference to your yarn link directory. You could do a goose chase to figure out where npm is grabbing it from, or you could consider just linking a new copy, then unlinking it cleanly.

I've tried with the easiest option first - linking & unlinking new copy, but the error did not go away (I've cleared the cache and even reboot after, just for sure).

I guess I'm only left with digging deeper into npm...

**Comment by BartoszKlonowski** [comment]
So I took a closer look at the Yarn directory and I found out that in
*C:\Users\Bartosz\AppData\Local\Yarn\bin* there is a *react-native-windows-init* script:
```
PS C:\Users\Bartosz> dir C:\Users\Bartosz\AppData\Local\Yarn\bin\

    Directory: C:\Users\Bartosz\AppData\Local\Yarn\bin

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        15.06.2021     13:55            355 react-native-windows-init
-a----        15.06.2021     13:55            232 react-native-windows-init.cmd

PS C:\Users\Bartosz>
```
After removing those, the `react-native-windows-init` runs just fine.
I don't really know or remember where did those come from, but at least the problem is resolved.

Thank you for all insights!
