### ISSUE TITLE
[UT Timeout] `getNpmVersion() is valid` -- `@react-native-windows/telemetry` -- `src/test/versionUtils.test.ts`

### ISSUE THREAD

**Issue by NickGerleman** [microsoft/react-native-windows#9183]
From CI, running on a quad-core machine with SSD, Node 16 with NPM 8.

https://dev.azure.com/ms/react-native-windows/_build/results?buildId=243798&view=logs&j=535198f9-5290-560b-cf5a-5b218edc34cc&t=d20bebb2-ce95-5535-0bb8-3ac674ec850d&l=2198

```
ERR!  FAIL  src/test/versionUtils.test.ts (7.5 s)
ERR!   √ getNodeVersion() is valid
ERR!   × getNpmVersion() is valid (5125 ms)
ERR!   √ getYarnVersion() is valid (1953 ms)
ERR!   √ getVisualStudioVersion() is valid (94 ms)
ERR!   √ getVersionOfNpmPackage() of empty string is null
ERR!   √ getVersionOfNpmPackage() of invalid package is null
ERR!   √ getVersionOfNpmPackage() of valid package is valid (16 ms)
ERR!   √ getVersionsOfNuGetPackages() of valid package in packages.config is valid (15 ms)
ERR!   √ getVersionsOfNuGetPackages() of invalid package in packages.config is invalid
ERR!   √ getVersionsOfNuGetPackages() of valid package in project is valid (16 ms)
ERR!   √ getVersionsOfNuGetPackages() of invalid package in project is invalid (16 ms)
ERR! 
ERR!   ● getNpmVersion() is valid
ERR! 
ERR!     : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
ERR! 
ERR!       32 | });
ERR!       33 |
ERR!     > 34 | test('getNpmVersion() is valid', async () => {
ERR!          | ^
ERR!       35 |   const node = await lookpath('npm');
ERR!       36 |   const version = await versionUtils.getNpmVersion();
ERR!       37 |   if (node) {
ERR! 
ERR!       at new Spec (../../../node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
ERR!       at Object.<anonymous> (src/test/versionUtils.test.ts:34:1)

```

![image](https://user-images.githubusercontent.com/835219/142608118-fb409c45-b055-4fde-b34d-b4e88b04f149.png)

**Comment by NickGerleman** [comment]
FYI @jonthysell
