### ISSUE TITLE
Error running yarn build codegen step in 0.66.7 release 

### ISSUE THREAD

**Issue by lyahdav** [microsoft/react-native-windows#9440]
### Problem Description

When I run `yarn build` on the [react-native-windows_v0.66.7 tag](https://github.com/microsoft/react-native-windows/releases/tag/react-native-windows_v0.66.7) I get the error below. When I do the same on `main` branch it works fine.
```
...
ERR! [12:59:42 PM] ■ finished 'compileTsPlatformOverrides' in 2.78s
ERR! [12:59:42 PM] ■ started 'codegen'
ERR! npm ERR! canceled
ERR!
ERR! npm ERR! A complete log of this run can be found in:
ERR! npm ERR!     C:\Users\lyahdav\AppData\Local\npm-cache\_logs\2022-01-28T20_59_43_831Z-debug.log
ERR! [12:59:43 PM] x Error detected while running 'codegen'
ERR! [12:59:43 PM] x ------------------------------------
ERR! [12:59:43 PM] x Error: Command failed: npx --no-install @react-native-windows/codegen --files Libraries/**/*[Nn]ative*.js --namespace Microsoft::ReactNativeSpecs --libraryName rnwcore
ERR! npm ERR! canceled
ERR!
ERR! npm ERR! A complete log of this run can be found in:
ERR! npm ERR!     C:\Users\lyahdav\AppData\Local\npm-cache\_logs\2022-01-28T20_59_43_831Z-debug.log
ERR!
ERR!     at checkExecSyncError (node:child_process:826:11)
ERR!     at execSync (node:child_process:900:15)
ERR!     at C:\Users\lyahdav\Documents\GitRepos\react-native-windows\vnext\just-task.js:29:3
ERR!     at _wrapFunction (C:\Users\lyahdav\Documents\GitRepos\react-native-windows\node_modules\just-task\lib\wrapTask.js:15:36)
ERR!     at taskWrapper (C:\Users\lyahdav\Documents\GitRepos\react-native-windows\node_modules\undertaker\lib\set-task.js:13:15)
ERR!     at bound (node:domain:421:15)
ERR!     at runBound (node:domain:432:12)
ERR!     at asyncRunner (C:\Users\lyahdav\Documents\GitRepos\react-native-windows\node_modules\async-done\index.js:55:18)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:78:11)
ERR! [12:59:43 PM] x stdout:
ERR! [12:59:43 PM] x <Buffer >
ERR! [12:59:43 PM] x stderr:
ERR! [12:59:43 PM] x <Buffer 6e 70 6d 20 45 52 52 21 20 63 61 6e 63 65 6c 65 64 0a 0a 6e 70 6d 20 45 52 52 21 20 41 20 63 6f 6d 70 6c 65 74 65 20 6c 6f 67 20 6f 66 20 74 68 69 73 ... 117 more bytes>
ERR! [12:59:43 PM] x ------------------------------------
ERR! [12:59:43 PM] x finished 'build' in 5.61s with errors
ERR! [12:59:43 PM] x Error previously detected. See above for error messages.
ERR! failed
info ----------------------------------------------
info Took a total of 9.67s to complete
error Command failed with exit code 1.
```

### Steps To Reproduce

1. Clone repo
2. `git checkout react-native-windows_v0.66.7`
3. `yarn`
4. `yarn build`

### Expected Results

`yarn build` succeeds

### CLI version

6.4.0

### Environment

```markdown
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.20348
    CPU: (16) x64 Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
    Memory: 43.10 GB / 62.54 GB
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.0-20190429.1820 - C:\open\fbsource\xplat\third-party\yarn\yarn.BAT
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20220124.100037 - C:\tools\watchman\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.18362.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.0.32112.339 (Visual Studio Professional 2022)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.60.0 is now available (your project is running on v0.0.0-20220107-2008-ca5aaa766).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.60.0.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.0.0-20220107-2008-ca5aaa766.
info To upgrade, run "react-native upgrade".
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by acoates-ms** [comment]
Try bumping down to node 14 when working in the 0.66 branch?

**Comment by lyahdav** [comment]
> Try bumping down to node 14 when working in the 0.66 branch?

Good call, that was it. I switched to node v14.18.3 and it worked. https://github.com/coreybutler/nvm-windows is very useful for this.
