### ISSUE TITLE
PRs failing to bundle new project with `TypeError: Cannot delete property 'resolveRequest' of #<Object>`

### ISSUE THREAD

**Issue by jonthysell** [microsoft/react-native-windows#9939]
### Problem Description

PRs are failing to bundle new app projects.

```
error Cannot delete property 'resolveRequest' of #<Object>.
TypeError: Cannot delete property 'resolveRequest' of #<Object>
    at D:\a\_work\1\testcli\node_modules\@react-native-community\cli-plugin-metro\build\tools\metroPlatformResolver.js:36:5
    at Object.resolve (D:\a\_work\1\testcli\node_modules\metro-resolver\src\resolve.js:31:12)
    at ModuleResolver.resolveDependency (D:\a\_work\1\testcli\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:115:31)
    at DependencyGraph.resolveDependency (D:\a\_work\1\testcli\node_modules\metro\src\node-haste\DependencyGraph.js:231:43)
    at Object.resolve (D:\a\_work\1\testcli\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (D:\a\_work\1\testcli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at D:\a\_work\1\testcli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (D:\a\_work\1\testcli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (D:\a\_work\1\testcli\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
```

### Steps To Reproduce

Example: https://dev.azure.com/ms/react-native-windows/_build/results?buildId=309233&view=logs&j=2421b910-b24d-531b-16c2-ae679493d42f&t=e4eeb9c4-0934-572e-61db-78ad43f3e6d2

### CLI version

npx react-native --version

### Environment

```markdown
npx react-native info
```

**Comment by jonthysell** [comment]
Currently investigating - I suspect there's a new metro (plugin) (minor) version that we get when creating a new project (but not in our yarn lock file for our repo) that's causing this.

**Comment by JunielKatarn** [comment]
Thanks.
This is blocking #9352.

**Comment by acoates-ms** [comment]
Looks like its probably from a breaking change in metro:
https://github.com/facebook/metro/commit/d81d8877c05637eac2b4ea946a9fa1e8ae869b06

Which breaks some code in the default metro config when bundling with an out of tree platform: https://github.com/react-native-community/cli/blob/0993f627869f4de0e5a8a9a950d38a9f15e18fb2/packages/cli-plugin-metro/src/tools/loadMetroConfig.ts#L74

**Comment by acoates-ms** [comment]
https://github.com/react-native-community/cli/pull/1605
I created a PR to the cli.
