### ISSUE TITLE
Cannot run unpacked app for CS WinUI3 WindowsAppSDK project

### ISSUE THREAD

**Issue by muramasa** [microsoft/react-native-windows#9975]
### Problem Description

When create unpackaged CS WinUI3 WindowsAppSDK RNW project, app cannot run.

The error is
```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.ReactNative.ReactApplication._IReactApplicationFactory.get_Instance()
   at Microsoft.ReactNative.ReactApplication..ctor()
   at csui3unpackaged.App..ctor() in C:\src\csui3unpackaged\windows\csui3unpackaged\App.xaml.cs:line 30
   at csui3unpackaged.Program.<>c.<Main>b__1_0(ApplicationInitializationCallbackParams p) in C:\src\csui3unpackaged\windows\csui3unpackaged\obj\x64\Debug\net5.0-windows10.0.19041.0\win10-x64\App.g.i.cs:line 34
   at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(ApplicationInitializationCallback invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.ApplicationInitializationCallback.Do_Abi_Invoke(IntPtr thisPtr, IntPtr p)

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.

Inner Exception 2:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
```

### Steps To Reproduce

1. $npx react-native init csui3unpackaged --template react-native@^0.68.0
2. $npx react-native-windows-init --useWinUI3 --overwrite --language cs --version 0.0.0-canary.501
3. [modify for unpackaged ](https://github.com/muramasa/csui3unpackaged/commit/d921f955391eb692025627366c4b5ae1c6682c38)

https://github.com/muramasa/csui3unpackaged/tree/d921f955391eb692025627366c4b5ae1c6682c38
This is the reproduce repo.

### Expected Results

can run app without issue

### CLI version

8.0.0

### Environment

```markdown
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 6.78 GB / 15.89 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32510.428 (Visual Studio Community 2019)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.0.0-20220501-2027-d992ae044 => 0.0.0-20220501-2027-d992ae044
    react-native-windows: 0.0.0-canary.501 => 0.0.0-canary.501
  npmGlobalPackages:
    *react-native*: Not Found
```

### Target Device(s)

Desktop

### Visual Studio Version

Visual Studio 2019

### Build Configuration

Debug

**Comment by muramasa** [comment]
I understood I miss "DynamicDependency" injection.
After injecting "Microsoft.VCLibs.140.00", I can run app for unpacked app
https://github.com/muramasa/csui3unpackaged/commit/687fc685b25704176050ff7236448fb453d7d444
